using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;

namespace CertificateManager.Infrastructure.Migrations;

/// <summary>
/// Baseline schema for fresh production databases. Existing databases created with
/// EnsureCreated must be verified and baselined before this migration is recorded.
/// </summary>
[DbContext(typeof(AppDbContext))]
[Migration("202608270001_InitialProductionSchema")]
public sealed class InitialProductionSchema : Migration
{
    protected override void Up(MigrationBuilder migrationBuilder)
    {
        migrationBuilder.Sql("""
            CREATE TABLE "AspNetRoles" (
                "Id" text PRIMARY KEY,
                "Name" varchar(256),
                "NormalizedName" varchar(256),
                "ConcurrencyStamp" text);
            CREATE UNIQUE INDEX "RoleNameIndex" ON "AspNetRoles" ("NormalizedName");

            CREATE TABLE "AspNetUsers" (
                "Id" text PRIMARY KEY,
                "DisplayName" text NOT NULL,
                "UserName" varchar(256),
                "NormalizedUserName" varchar(256),
                "Email" varchar(256),
                "NormalizedEmail" varchar(256),
                "EmailConfirmed" boolean NOT NULL,
                "PasswordHash" text,
                "SecurityStamp" text,
                "ConcurrencyStamp" text,
                "PhoneNumber" text,
                "PhoneNumberConfirmed" boolean NOT NULL,
                "TwoFactorEnabled" boolean NOT NULL,
                "LockoutEnd" timestamp with time zone,
                "LockoutEnabled" boolean NOT NULL,
                "AccessFailedCount" integer NOT NULL);
            CREATE INDEX "EmailIndex" ON "AspNetUsers" ("NormalizedEmail");
            CREATE UNIQUE INDEX "UserNameIndex" ON "AspNetUsers" ("NormalizedUserName");

            CREATE TABLE "AspNetRoleClaims" (
                "Id" integer GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
                "RoleId" text NOT NULL REFERENCES "AspNetRoles" ("Id") ON DELETE CASCADE,
                "ClaimType" text,
                "ClaimValue" text);
            CREATE INDEX "IX_AspNetRoleClaims_RoleId" ON "AspNetRoleClaims" ("RoleId");

            CREATE TABLE "AspNetUserClaims" (
                "Id" integer GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
                "UserId" text NOT NULL REFERENCES "AspNetUsers" ("Id") ON DELETE CASCADE,
                "ClaimType" text,
                "ClaimValue" text);
            CREATE INDEX "IX_AspNetUserClaims_UserId" ON "AspNetUserClaims" ("UserId");

            CREATE TABLE "AspNetUserLogins" (
                "LoginProvider" text NOT NULL,
                "ProviderKey" text NOT NULL,
                "ProviderDisplayName" text,
                "UserId" text NOT NULL REFERENCES "AspNetUsers" ("Id") ON DELETE CASCADE,
                PRIMARY KEY ("LoginProvider", "ProviderKey"));
            CREATE INDEX "IX_AspNetUserLogins_UserId" ON "AspNetUserLogins" ("UserId");

            CREATE TABLE "AspNetUserRoles" (
                "UserId" text NOT NULL REFERENCES "AspNetUsers" ("Id") ON DELETE CASCADE,
                "RoleId" text NOT NULL REFERENCES "AspNetRoles" ("Id") ON DELETE CASCADE,
                PRIMARY KEY ("UserId", "RoleId"));
            CREATE INDEX "IX_AspNetUserRoles_RoleId" ON "AspNetUserRoles" ("RoleId");

            CREATE TABLE "AspNetUserTokens" (
                "UserId" text NOT NULL REFERENCES "AspNetUsers" ("Id") ON DELETE CASCADE,
                "LoginProvider" text NOT NULL,
                "Name" text NOT NULL,
                "Value" text,
                PRIMARY KEY ("UserId", "LoginProvider", "Name"));

            CREATE TABLE "Customers" (
                "Id" uuid PRIMARY KEY,
                "Name" text NOT NULL,
                "Description" text NOT NULL,
                "CustomerNumber" text,
                "IsActive" boolean NOT NULL,
                "CreatedAt" timestamp with time zone NOT NULL,
                "UpdatedAt" timestamp with time zone NOT NULL);
            CREATE INDEX "IX_Customers_Name" ON "Customers" ("Name");

            CREATE TABLE "Environments" (
                "Id" uuid PRIMARY KEY,
                "CustomerId" uuid NOT NULL REFERENCES "Customers" ("Id") ON DELETE CASCADE,
                "Name" text NOT NULL,
                "Description" text NOT NULL,
                "TenantReference" text,
                "EnvironmentType" integer NOT NULL,
                "IsActive" boolean NOT NULL,
                "CreatedAt" timestamp with time zone NOT NULL,
                "UpdatedAt" timestamp with time zone NOT NULL);
            CREATE INDEX "IX_Environments_CustomerId" ON "Environments" ("CustomerId");

            CREATE TABLE "Services" (
                "Id" uuid PRIMARY KEY,
                "EnvironmentId" uuid NOT NULL REFERENCES "Environments" ("Id") ON DELETE CASCADE,
                "Name" text NOT NULL,
                "Description" text NOT NULL,
                "ApplicationClientId" text,
                "ExternalReference" text,
                "IsActive" boolean NOT NULL,
                "CreatedAt" timestamp with time zone NOT NULL,
                "UpdatedAt" timestamp with time zone NOT NULL);
            CREATE INDEX "IX_Services_EnvironmentId" ON "Services" ("EnvironmentId");

            CREATE TABLE "Certificates" (
                "Id" uuid PRIMARY KEY,
                "ServiceId" uuid NOT NULL REFERENCES "Services" ("Id") ON DELETE CASCADE,
                "Name" text NOT NULL,
                "Subject" text NOT NULL,
                "Issuer" text NOT NULL,
                "Thumbprint" text NOT NULL,
                "SerialNumber" text NOT NULL,
                "Algorithm" text NOT NULL,
                "KeySize" integer NOT NULL,
                "HashAlgorithm" text NOT NULL,
                "ValidFrom" timestamp with time zone NOT NULL,
                "ValidUntil" timestamp with time zone NOT NULL,
                "RenewalDueAt" timestamp with time zone NOT NULL,
                "CreatedByUserId" text NOT NULL,
                "PrimaryOwnerEmail" text NOT NULL,
                "Status" integer NOT NULL,
                "PreviousCertificateId" uuid,
                "ReplacementCertificateId" uuid,
                "DeploymentStatus" integer NOT NULL,
                "DeploymentConfirmedAt" timestamp with time zone,
                "DeploymentConfirmedByUserId" text,
                "Notes" text,
                "DecommissionedAt" timestamp with time zone,
                "DecommissionedByUserId" text,
                "DecommissionReason" text,
                "CreatedAt" timestamp with time zone NOT NULL,
                "UpdatedAt" timestamp with time zone NOT NULL);
            CREATE INDEX "IX_Certificates_ServiceId" ON "Certificates" ("ServiceId");
            CREATE INDEX "IX_Certificates_ValidUntil" ON "Certificates" ("ValidUntil");
            CREATE INDEX "IX_Certificates_PrimaryOwnerEmail" ON "Certificates" ("PrimaryOwnerEmail");
            CREATE INDEX "IX_Certificates_Status" ON "Certificates" ("Status");
            CREATE UNIQUE INDEX "IX_Certificates_Thumbprint" ON "Certificates" ("Thumbprint");

            CREATE TABLE "NotificationHistory" (
                "Id" uuid PRIMARY KEY,
                "CertificateId" uuid NOT NULL,
                "NotificationType" text NOT NULL,
                "Recipient" text NOT NULL,
                "SentAt" timestamp with time zone NOT NULL,
                "DaysBeforeExpiration" integer NOT NULL,
                "Success" boolean NOT NULL,
                "CreatedAt" timestamp with time zone NOT NULL,
                "UpdatedAt" timestamp with time zone NOT NULL);
            CREATE UNIQUE INDEX "IX_NotificationHistory_CertificateId_DaysBeforeExpiration_Recipient"
                ON "NotificationHistory" ("CertificateId", "DaysBeforeExpiration", "Recipient");

            CREATE TABLE "AuditLogs" (
                "Id" bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
                "Timestamp" timestamp with time zone NOT NULL,
                "UserId" text,
                "Action" text NOT NULL,
                "EntityType" text NOT NULL,
                "EntityId" text,
                "IpAddress" text,
                "Result" text NOT NULL,
                "Metadata" jsonb);

            CREATE TABLE "MailProviderSettings" (
                "Id" integer PRIMARY KEY,
                "Enabled" boolean NOT NULL,
                "Host" text NOT NULL,
                "Port" integer NOT NULL,
                "Username" text NOT NULL,
                "ProtectedPassword" text NOT NULL,
                "From" text NOT NULL,
                "UpdatedAt" timestamp with time zone NOT NULL);

            CREATE TABLE "NotificationSettings" (
                "Id" integer PRIMARY KEY,
                "Enabled" boolean NOT NULL,
                "InitialDelaySeconds" integer NOT NULL,
                "IntervalHours" integer NOT NULL,
                "Milestones" text NOT NULL,
                "UpdatedAt" timestamp with time zone NOT NULL);
            """);
    }

    protected override void Down(MigrationBuilder migrationBuilder)
    {
        migrationBuilder.Sql("""
            DROP TABLE IF EXISTS "NotificationSettings", "MailProviderSettings", "AuditLogs",
                "NotificationHistory", "Certificates", "Services", "Environments", "Customers",
                "AspNetUserTokens", "AspNetUserRoles", "AspNetUserLogins", "AspNetUserClaims",
                "AspNetRoleClaims", "AspNetUsers", "AspNetRoles" CASCADE;
            """);
    }
}
