namespace CertificateManager.Domain;

public abstract class Entity { public Guid Id { get; set; } = Guid.NewGuid(); public DateTimeOffset CreatedAt { get; set; } = DateTimeOffset.UtcNow; public DateTimeOffset UpdatedAt { get; set; } = DateTimeOffset.UtcNow; }
public sealed class Customer : Entity { public required string Name { get; set; } public string Description { get; set; } = ""; public string? CustomerNumber { get; set; } public bool IsActive { get; set; } = true; public ICollection<TargetEnvironment> Environments { get; set; } = []; }
public enum EnvironmentType { Production, Development, Testing, Staging, Other }
public sealed class TargetEnvironment : Entity { public Guid CustomerId { get; set; } public Customer Customer { get; set; } = null!; public required string Name { get; set; } public string Description { get; set; } = ""; public string? TenantReference { get; set; } public EnvironmentType EnvironmentType { get; set; } public bool IsActive { get; set; } = true; public ICollection<ManagedService> Services { get; set; } = []; }
public sealed class ManagedService : Entity { public Guid EnvironmentId { get; set; } public TargetEnvironment Environment { get; set; } = null!; public required string Name { get; set; } public string Description { get; set; } = ""; public string? ApplicationClientId { get; set; } public string? ExternalReference { get; set; } public bool IsActive { get; set; } = true; public ICollection<CertificateRecord> Certificates { get; set; } = []; }
public enum CertificateStatus { Active, RenewalUpcoming, RenewalRequired, Expired, Renewed, Superseded, Decommissioned }
public enum DeploymentStatus { Generated, Downloaded, DeploymentPending, DeploymentConfirmed, Superseded }
public sealed class CertificateRecord : Entity {
 public Guid ServiceId { get; set; } public ManagedService Service { get; set; } = null!; public required string Name { get; set; } public required string Subject { get; set; } public required string Issuer { get; set; } public required string Thumbprint { get; set; } public required string SerialNumber { get; set; } public string Algorithm { get; set; } = "RSA"; public int KeySize { get; set; } = 3072; public string HashAlgorithm { get; set; } = "SHA256"; public DateTimeOffset ValidFrom { get; set; } public DateTimeOffset ValidUntil { get; set; } public DateTimeOffset RenewalDueAt { get; set; } public required string CreatedByUserId { get; set; } public required string PrimaryOwnerEmail { get; set; } public CertificateStatus Status { get; set; } = CertificateStatus.Active; public Guid? PreviousCertificateId { get; set; } public Guid? ReplacementCertificateId { get; set; } public DeploymentStatus DeploymentStatus { get; set; } = DeploymentStatus.Generated; public DateTimeOffset? DeploymentConfirmedAt { get; set; } public string? DeploymentConfirmedByUserId { get; set; } public string? Notes { get; set; }
}
public sealed class NotificationHistory : Entity { public Guid CertificateId { get; set; } public string NotificationType { get; set; } = "Renewal"; public required string Recipient { get; set; } public DateTimeOffset SentAt { get; set; } public int DaysBeforeExpiration { get; set; } public bool Success { get; set; } }
public sealed class AuditLog { public long Id { get; set; } public DateTimeOffset Timestamp { get; set; } = DateTimeOffset.UtcNow; public string? UserId { get; set; } public required string Action { get; set; } public required string EntityType { get; set; } public string? EntityId { get; set; } public string? IpAddress { get; set; } public required string Result { get; set; } public string? Metadata { get; set; } }
