import React, {useEffect, useMemo, useState} from 'react';
import {createRoot} from 'react-dom/client';
import {Activity, Building2, CalendarClock, ClipboardList, Download, FileKey2, LayoutDashboard, LogOut, Plus, RefreshCw, Search, ShieldCheck, X} from 'lucide-react';
import './styles.css';
import './interaction.css';
type Dashboard = {total:number;
 healthy:number;
 expiring60:number;
 expiring30:number;
 expiring14:number;
 critical:number;
 expired:number};
type Customer = {id:string;
 name:string;
 description:string;
 customerNumber?:string;
 isActive:boolean};
type Service = {id:string;
 name:string;
 description:string;
 customerId:string;
 customer:string;
 applicationClientId?:string;
 externalReference?:string;
 isActive:boolean;
 certificateReady?:boolean};
type Cert = {id:string;
 name:string;
 subject:string;
 serviceId:string;
 thumbprint:string;
 validUntil:string;
 daysRemaining:number;
 health:string;
 status:string;
 primaryOwnerEmail:string;
 deploymentStatus:string;
 service:string;
 customer:string;
 decommissionedAt?:string;
 decommissionReason?:string};
type CertificateDetail = Cert & {issuer:string;
 serialNumber:string;
 algorithm:string;
 keySize:number;
 hashAlgorithm:string;
 validFrom:string;
 renewalDueAt:string;
 status:string;
 notes?:string};
type RenewalDraft = {serviceId:string;
 name:string;
 commonName:string;
 owner:string;
 previousCertificateId:string};
type Audit = {id:string;
 timestamp:string;
 action:string;
 entityType:string;
 entityId:string;
 result:string;
 userId?:string};
type Generated = {name:string;
 password:string;
 pfx:string;
 cer:string;
 package:string;
 calendar:string;
 thumbprint:string};
type AdminUser = {id:string;
 email:string;
 displayName:string;
 roles:string[];
 emailConfirmed:boolean;
 lockoutEnd?:string};
type Integrations = {api:{openApi:boolean;
 basePath:string;
 authentication:string};
 mail:{enabled:boolean;
 host:string;
 port:number;
 username:string;
 from:string;
 configured:boolean;
 credentialsConfigured:boolean}};
type NotificationStatus = {enabled:boolean;
 initialDelaySeconds:number;
 intervalHours:number;
 milestones:number[];
 lastSentAt?:string};
type Page = 'Dashboard'|'Certificates'|'Customers'|'Services'|'Renewals'|'Admin'|'Audit';
let antiforgeryToken:string|undefined;
let antiforgeryRequest:Promise<string>|undefined;
let currentRoles:string[]=[];
const getAntiforgeryToken = async(forceRefresh=false) => {if(!forceRefresh&&antiforgeryToken)return antiforgeryToken;
if(antiforgeryRequest)return antiforgeryRequest;
const request=(async()=>{const response=await fetch('/api/antiforgery',{credentials:'include',cache:'no-store',headers:{Accept:'application/json'}});
if(!response.ok)throw new Error('Could not initialize request security');
const body=await response.json() as {token?:string};
if(!body.token)throw new Error('Could not initialize request security');
antiforgeryToken=body.token;
return body.token;
})();
antiforgeryRequest=request;
try{return await request;}finally{if(antiforgeryRequest===request)antiforgeryRequest=undefined;}
};
const api = async <T,>(path:string, init?:RequestInit, retryAntiforgery=true):Promise<T> => {const method=(init?.method??'GET').toUpperCase();
const mutation=!['GET','HEAD','OPTIONS'].includes(method);
const headers=new Headers(init?.headers);
if(mutation)headers.set('Content-Type','application/json');
if(mutation&&path!=='/auth/login')headers.set('X-XSRF-TOKEN',await getAntiforgeryToken(true));
const response=await fetch('/api'+path,{credentials:'include',...init,headers});
if(!response.ok){let detail='';
try{const body=await response.json() as {error?:string};
detail=body.error??'';
}catch{}if(response.status===400&&detail==='Invalid antiforgery token'&&retryAntiforgery&&mutation&&path!=='/auth/login'){antiforgeryToken=undefined;
await getAntiforgeryToken(true);
return api<T>(path,init,false);
}if(response.status===401)window.dispatchEvent(new Event('auth-expired'));throw new Error(detail|| (response.status===401?'Authentication required':`Request failed (${response.status})`));
}return response.status===204?undefined as T:response.json();
};
function Login({done}:{done:()=>void}) {const [email,setEmail]=useState('admin@localhost'),[password,setPassword]=useState(''),[error,setError]=useState(''),[busy,setBusy]=useState(false),[microsoftEnabled,setMicrosoftEnabled]=useState(false);
 useEffect(()=>{api<{microsoft:{enabled:boolean}}>('/auth/providers').then(value=>setMicrosoftEnabled(value.microsoft.enabled)).catch(()=>{});const params=new URLSearchParams(window.location.search);const providerError=params.get('microsoftError');if(providerError){setError(providerError==='account-locked'?'Your Microsoft-linked account is locked.':providerError==='missing-email'?'Microsoft did not provide an email address.':providerError==='account-creation-failed'?'Your Microsoft account could not be provisioned.':'Microsoft sign-in failed. Please try again.');window.history.replaceState({},document.title,window.location.pathname);}},[]);
return <main className="login"><form onSubmit={async event=>{event.preventDefault();
if(busy)return;
setError('');
setBusy(true);
try{await api('/auth/login',{method:'POST',body:JSON.stringify({email:email.trim(),password})});
antiforgeryToken=undefined;
setPassword('');
done();
}catch(e){setError(e instanceof Error?e.message:'Sign-in failed.');
}finally{setBusy(false);
 }}}><div className="brandmark"><ShieldCheck/></div><h1>Certificate Lifecycle Manager</h1><p>Sign in with your local operator account.</p><label>Email<input value={email} onChange={event=>setEmail(event.target.value)} type="email" autoComplete="username" required/></label><label>Password<input value={password} onChange={event=>setPassword(event.target.value)} type="password" autoComplete="current-password" required/></label>{error&&<div className="error" role="alert">{error}</div>}<button type="submit" disabled={busy}>{busy?'Signing in...':'Sign in securely'}</button>{microsoftEnabled&&<><div className="loginDivider"><span>or</span></div><button type="button" className="microsoftButton" onClick={()=>window.location.assign('/api/auth/microsoft')} disabled={busy}>Continue with Microsoft</button></>}<small className="fieldHint">Use the password configured by <code>SEED_ADMIN_PASSWORD</code>, or your Microsoft work account.</small></form></main>;
}
function PasswordDialog({close,done}:{close:()=>void;done:()=>void}) {const [current,setCurrent]=useState(''),[next,setNext]=useState(''),[confirm,setConfirm]=useState(''),[error,setError]=useState(''),[saving,setSaving]=useState(false);const submit=async(event:React.FormEvent)=>{event.preventDefault();setSaving(true);setError('');try{await api('/auth/password',{method:'POST',body:JSON.stringify({currentPassword:current,newPassword:next,confirmPassword:confirm})});done();}catch(e){setError(e instanceof Error?e.message:'Could not change password.');}finally{setSaving(false);}};return <div className="modalBackdrop"><form className="modal" onSubmit={submit}><div className="modalHead"><div><h2>Change password</h2><p>Use a strong password with at least 12 characters.</p></div><button type="button" className="iconButton" onClick={close} aria-label="Close"><X size={18}/></button></div><label>Current password<input type="password" value={current} onChange={event=>setCurrent(event.target.value)} autoComplete="current-password" required/></label><label>New password<input type="password" value={next} onChange={event=>setNext(event.target.value)} minLength={12} autoComplete="new-password" required/></label><label>Confirm new password<input type="password" value={confirm} onChange={event=>setConfirm(event.target.value)} minLength={12} autoComplete="new-password" required/></label>{error&&<div className="error">{error}</div>}<button className="primary" disabled={saving}>{saving?'Saving...':'Change password'}</button></form></div>;}
function CreateDialog({kind,customers,close,done}:{kind:'customer'|'service';customers:Customer[];close:()=>void;done:()=>void}) {const activeCustomers=customers.filter(customer=>customer.isActive);const [name,setName]=useState(''),[customerId,setCustomerId]=useState(activeCustomers[0]?.id??''),[clientId,setClientId]=useState(''),[externalRef,setExternalRef]=useState(''),[error,setError]=useState(''),[saving,setSaving]=useState(false);const title=kind==='customer'?'Create customer':'Create service';const missing=kind==='service'&&!activeCustomers.length;const submit=async(event:React.FormEvent)=>{event.preventDefault();setSaving(true);const body=kind==='customer'?{name,description:'',customerNumber:null}:{customerId,name,description:'',applicationClientId:clientId||null,externalReference:externalRef||null};try{await api(kind==='customer'?'/customers':'/services',{method:'POST',body:JSON.stringify(body)});done();}catch(e){setError(e instanceof Error?e.message:'Could not save record.');}finally{setSaving(false);}};return <div className="modalBackdrop"><form className="modal" onSubmit={submit}><div className="modalHead"><h2>{title}</h2><button type="button" className="iconButton" onClick={close} aria-label="Close"><X size={18}/></button></div>{missing?<p className="error">Create or restore a customer before adding a service.</p>:<>{kind==='service'&&<label>Customer<select value={customerId} onChange={event=>setCustomerId(event.target.value)} required>{activeCustomers.map(customer=><option key={customer.id} value={customer.id}>{customer.name}</option>)}</select></label>}<label>Name<input value={name} onChange={event=>setName(event.target.value)} required autoFocus/></label>{kind==='service'&&<><label>Application (client) ID<input value={clientId} onChange={event=>setClientId(event.target.value)} placeholder="Optional service principal client ID"/></label><label>External reference<input value={externalRef} onChange={event=>setExternalRef(event.target.value)} placeholder="Optional inventory reference"/></label></>}{error&&<div className="error">{error}</div>}<button className="primary" disabled={saving}>{saving?'Saving...':title}</button></>}</form></div>;}
function EditDialog({kind,record,close,done}:{kind:'customer'|'service';record:Customer|Service;close:()=>void;done:()=>void}) {const customer=kind==='customer'?record as Customer:undefined;const service=kind==='service'?record as Service:undefined;const [name,setName]=useState(record.name),[description,setDescription]=useState(record.description??''),[customerNumber,setCustomerNumber]=useState(customer?.customerNumber??''),[clientId,setClientId]=useState(service?.applicationClientId??''),[externalRef,setExternalRef]=useState(service?.externalReference??''),[error,setError]=useState(''),[saving,setSaving]=useState(false);const title=kind==='customer'?'Edit customer':'Edit service';const submit=async(event:React.FormEvent)=>{event.preventDefault();setSaving(true);try{const body=kind==='customer'?{name,description,customerNumber:customerNumber||null}:{name,description,applicationClientId:clientId||null,externalReference:externalRef||null};await api(`/${kind==='customer'?'customers':'services'}/${record.id}`,{method:'PUT',body:JSON.stringify(body)});done();}catch(e){setError(e instanceof Error?e.message:'Could not update record.');}finally{setSaving(false);}};return <div className="modalBackdrop"><form className="modal" onSubmit={submit}><div className="modalHead"><h2>{title}</h2><button type="button" className="iconButton" onClick={close} aria-label="Close"><X size={18}/></button></div><label>Name<input value={name} onChange={event=>setName(event.target.value)} required autoFocus/></label><label>Description<textarea value={description} onChange={event=>setDescription(event.target.value)} rows={3}/></label>{kind==='customer'?<label>Customer number<input value={customerNumber} onChange={event=>setCustomerNumber(event.target.value)}/></label>:<><label>Application (client) ID<input value={clientId} onChange={event=>setClientId(event.target.value)}/></label><label>External reference<input value={externalRef} onChange={event=>setExternalRef(event.target.value)}/></label></>}{error&&<div className="error">{error}</div>}<button className="primary" disabled={saving}>{saving?'Saving...':'Save changes'}</button></form></div>;}
function GenerateDialog({services,initial,close,done}:{services:Service[];
initial?:RenewalDraft;
close:()=>void;
done:(result:Generated)=>void}) {const [serviceId,setServiceId]=useState(initial?.serviceId??services[0]?.id??''),[name,setName]=useState(initial?.name??''),[commonName,setCommonName]=useState(initial?.commonName??''),[owner,setOwner]=useState(initial?.owner??''),[days,setDays]=useState('365'),[reminder,setReminder]=useState('30'),[keySize,setKeySize]=useState('3072'),[hashAlgorithm,setHashAlgorithm]=useState('SHA256'),[useCase,setUseCase]=useState('0'),[notes,setNotes]=useState(''),[error,setError]=useState(''),[saving,setSaving]=useState(false);
const selectedService=services.find(service=>service.id===serviceId);
const submit=async(event:React.FormEvent)=>{event.preventDefault();
setSaving(true);
try{const result=await api<Generated>('/certificates/generate',{method:'POST',body:JSON.stringify({serviceId,name,commonName,validityDays:Number(days),renewalReminderDays:Number(reminder),keySize:Number(keySize),hashAlgorithm,primaryOwnerEmail:owner,useCase:Number(useCase),notes:notes||null,previousCertificateId:initial?.previousCertificateId??null})});
done(result);
}catch(e){setError(e instanceof Error?e.message:'Could not generate certificate.');
}finally{setSaving(false);
}};
return <div className="modalBackdrop"><form className="modal" onSubmit={submit}><div className="modalHead"><h2>Generate certificate</h2><button type="button" className="iconButton" onClick={close} aria-label="Close"><X size={18}/></button></div>{!services.length?<p className="error">Create a service before generating a certificate.</p>:<><label>Service<select value={serviceId} onChange={event=>setServiceId(event.target.value)} required>{services.map(service=><option key={service.id} value={service.id}>{service.name}</option>)}</select></label>{useCase==='0'&&!selectedService?.applicationClientId&&<div className="notice">This service has no Application (client) ID. Add one before using the certificate for service-principal sign-in.</div>}<label>Certificate name<input value={name} onChange={event=>setName(event.target.value)} required/></label><label>Common name<input value={commonName} onChange={event=>setCommonName(event.target.value)} required/></label><label>Primary owner email<input value={owner} onChange={event=>setOwner(event.target.value)} type="email" required/></label><div className="formGrid"><label>Validity (days)<input value={days} onChange={event=>setDays(event.target.value)} type="number" min="1" max="3650" required/></label><label>Renewal reminder (days)<input value={reminder} onChange={event=>setReminder(event.target.value)} type="number" min="1" max={days} required/></label></div><label>Key size<select value={keySize} onChange={event=>setKeySize(event.target.value)}><option value="2048">2048-bit (standard)</option><option value="3072">3072-bit (recommended)</option><option value="4096">4096-bit (strongest)</option></select></label><label>Signature hash<select value={hashAlgorithm} onChange={event=>setHashAlgorithm(event.target.value)}><option value="SHA256">SHA-256 (recommended)</option><option value="SHA384">SHA-384</option><option value="SHA512">SHA-512</option></select></label><label>Operator notes<textarea value={notes} onChange={event=>setNotes(event.target.value)} rows={2} placeholder="Optional deployment or ownership note"/></label><div className="fieldGroup"><label>Certificate purpose<select value={useCase} onChange={event=>setUseCase(event.target.value)}><option value="0">Service principal sign-in (recommended)</option><option value="1">Server authentication (TLS)</option><option value="2">Client and server authentication</option></select></label><small className="fieldHint">Service principal sign-ins use the Client Authentication EKU for certificate-based assertions.</small></div>{error&&<div className="error">{error}</div>}<button className="primary" disabled={saving}>{saving?'Generating...':'Generate certificate'}</button></>}</form></div>;
}
function ArtifactDialog({result,close}:{result:Generated;
close:()=>void}) {const [downloaded,setDownloaded]=useState<string[]>([]),[copied,setCopied]=useState('');const download=(data:string,name:string,type:string)=>{const link=document.createElement('a');
link.href=`data:${type};base64,${data}`;
link.download=name;
link.click();
setDownloaded(value=>value.includes(name)?value:[...value,name]);
};
const copy=async(value:string,label:string)=>{await navigator.clipboard.writeText(value);setCopied(label);window.setTimeout(()=>setCopied(''),1800);};const safelyClose=()=>{const hasPrivateKey=downloaded.some(name=>name.endsWith('.pfx')||name.endsWith('.zip'));if(hasPrivateKey||window.confirm('The private key has not been downloaded. Close anyway?'))close();};
return <div className="modalBackdrop"><div className="modal"><div className="modalHead"><h2>Certificate generated</h2><button type="button" className="iconButton" onClick={safelyClose} aria-label="Close"><X size={18}/></button></div><p className="notice">Save these artifacts now. The password and private key are not stored for later download.</p><label>One-time PFX password<div className="copyField"><input readOnly value={result.password}/><button type="button" onClick={()=>copy(result.password,'password')}>{copied==='password'?'Copied':'Copy'}</button></div></label><p>Thumbprint: <code>{result.thumbprint}</code> <button className="copyButton inlineCopy" type="button" onClick={()=>copy(result.thumbprint,'thumbprint')}>{copied==='thumbprint'?'Copied':'Copy'}</button></p><div className="artifactLinks"><button className="primary" onClick={()=>download(result.pfx,`${result.name}.pfx`,'application/x-pkcs12')}>{downloaded.includes(`${result.name}.pfx`)?'Downloaded PFX':'Download PFX'}</button><button onClick={()=>download(result.cer,`${result.name}.cer`,'application/x-x509-ca-cert')}>Download CER</button><button onClick={()=>download(result.package,`${result.name}.zip`,'application/zip')}>{downloaded.includes(`${result.name}.zip`)?'Downloaded package':'Download package'}</button><button onClick={()=>download(result.calendar,`${result.name}-renewal.ics`,'text/calendar')}>Download calendar</button></div><button className="primary" onClick={safelyClose}>Done</button></div></div>}
function CertificateTable({certs,reload,renew,inspect,canOperate,canAdmin,empty='No certificates yet'}:{certs:Cert[];
reload:()=>void;
renew?:(cert:Cert)=>void;
 inspect?:(cert:Cert)=>void;
 canOperate?:boolean;
 canAdmin?:boolean;
 empty?:string}) {canOperate??=currentRoles.includes('CertificateOperator')||currentRoles.includes('Administrator');canAdmin??=currentRoles.includes('Administrator');const [busy,setBusy]=useState(''),[copied,setCopied]=useState(''),[error,setError]=useState('');
const copy=async(cert:Cert)=>{try{await navigator.clipboard.writeText(cert.thumbprint);
setCopied(cert.id);
setTimeout(()=>setCopied(''),1800);
}catch{}};
 const action=async(id:string,path:string,body?:unknown)=>{setBusy(id);setError('');
 try{await api(`/certificates/${id}/${path}`,{method:'POST',...(body===undefined?{}:{body:JSON.stringify(body)})});
reload();
 }catch(e){setError(e instanceof Error?e.message:'Could not update certificate.');}finally{setBusy('');
}};
 return <>{error&&<div className="error" role="alert">{error}</div>}{certs.length?<div className="tableWrap"><table><thead><tr><th>Customer</th><th>Application</th><th>Certificate</th><th>Valid until</th><th>Owner</th><th>Health</th><th>Status</th><th>Actions</th></tr></thead><tbody>{certs.map(cert=>{const historical=cert.status==='Renewed'||cert.status==='Superseded';return <tr key={cert.id}><td><b>{cert.customer}</b></td><td>{cert.service}</td><td><b>{cert.name}</b><code>{cert.thumbprint.slice(0,12)}...</code><button className="copyButton" onClick={()=>copy(cert)}>{copied===cert.id?'Copied':'Copy thumbprint'}</button></td><td>{new Date(cert.validUntil).toLocaleDateString()}<span>{cert.daysRemaining} days</span></td><td>{cert.primaryOwnerEmail}</td><td><i className={'badge '+cert.health.toLowerCase()}>{cert.health}</i></td><td><i className={'badge '+(historical?'expired':'healthy')}>{cert.status}</i></td><td className="actions">{inspect&&<button onClick={()=>inspect(cert)}>Details</button>}<button onClick={()=>window.open(`/api/certificates/${cert.id}/calendar`,'_blank')}>Calendar</button>{renew&&(canOperate!==false)&&!historical&&<button onClick={()=>renew(cert)}><RefreshCw size={14}/>Renew</button>}{(canOperate!==false)&&!historical&&cert.deploymentStatus!=='DeploymentConfirmed'&&<button disabled={busy===cert.id} onClick={()=>action(cert.id,'mark-deployed')}>Mark deployed</button>}{(canAdmin!==false)&&!historical&&<button disabled={busy===cert.id} onClick={()=>{const reason=window.prompt('Why is this certificate being retired? (optional)');if(reason!==null)action(cert.id,'decommission',{reason});}}>Decommission</button>}</td></tr>})}</tbody></table></div>:<div className="empty"><FileKey2/><h3>{empty}</h3></div>}</>;
}
function CertificateDetailDialog({id,close}:{id:string;close:()=>void}){const [detail,setDetail]=useState<CertificateDetail|null>(null),[error,setError]=useState('');useEffect(()=>{api<{certificate:CertificateDetail;health:string}>('/certificates/'+id).then(value=>setDetail({...value.certificate,health:value.health})).catch(e=>setError(e instanceof Error?e.message:'Could not load certificate details.'));},[id]);return <div className="modalBackdrop"><div className="modal detailModal"><div className="modalHead"><div><h2>Certificate details</h2><p>Lifecycle metadata and deployment readiness.</p></div><button type="button" className="iconButton" onClick={close} aria-label="Close"><X size={18}/></button></div>{error&&<div className="error">{error}</div>}{!detail&&!error&&<p>Loading certificate details...</p>}{detail&&<><div className="detailHero"><div><b>{detail.name}</b><span>{detail.customer} / {detail.service}</span></div><i className={'badge '+detail.health.toLowerCase()}>{detail.health}</i></div><dl className="detailGrid"><dt>Subject</dt><dd>{detail.subject}</dd><dt>Thumbprint</dt><dd><code>{detail.thumbprint}</code></dd><dt>Serial number</dt><dd><code>{detail.serialNumber}</code></dd><dt>Algorithm</dt><dd>{detail.algorithm} {detail.keySize}-bit / {detail.hashAlgorithm}</dd><dt>Valid from</dt><dd>{new Date(detail.validFrom).toLocaleString()}</dd><dt>Valid until</dt><dd>{new Date(detail.validUntil).toLocaleString()}</dd><dt>Renewal due</dt><dd>{new Date(detail.renewalDueAt).toLocaleString()}</dd><dt>Owner</dt><dd>{detail.primaryOwnerEmail}</dd><dt>Deployment</dt><dd>{detail.deploymentStatus}</dd></dl>{detail.notes&&<div className="notice">{detail.notes}</div>}<button className="primary" onClick={()=>window.open('/api/certificates/'+detail.id+'/calendar','_blank')}>Download renewal calendar</button></>}</div></div>;}
function AdminPanel(){
 const [users,setUsers]=useState<AdminUser[]>([]);
 const [integrations,setIntegrations]=useState<Integrations|null>(null);
 const [notifications,setNotifications]=useState<NotificationStatus|null>(null);
 const [error,setError]=useState('');
 const [mailError,setMailError]=useState('');
 const [mailMessage,setMailMessage]=useState('');
 const [mailEnabled,setMailEnabled]=useState(false);
 const [mailHost,setMailHost]=useState('');
 const [mailPort,setMailPort]=useState('587');
 const [mailUsername,setMailUsername]=useState('');
 const [mailPassword,setMailPassword]=useState('');
 const [mailFrom,setMailFrom]=useState('');
 const [testRecipient,setTestRecipient]=useState('');
 const [newEmail,setNewEmail]=useState('');
 const [newDisplayName,setNewDisplayName]=useState('');
 const [newPassword,setNewPassword]=useState('');
 const [newRole,setNewRole]=useState('Reader');
 const [saving,setSaving]=useState(false);
 const [mailSaving,setMailSaving]=useState(false);
 const [testing,setTesting]=useState(false);
  const [notificationSaving,setNotificationSaving]=useState(false);
  const [notificationError,setNotificationError]=useState('');
  const [notificationMessage,setNotificationMessage]=useState('');
  const [notificationEnabled,setNotificationEnabled]=useState(false);
  const [notificationInitialDelay,setNotificationInitialDelay]=useState('30');
  const [notificationInterval,setNotificationInterval]=useState('24');
 const [notificationMilestones,setNotificationMilestones]=useState('60,30,14,7,1,0');
 const load=()=>{api<AdminUser[]>('/admin/users').then(setUsers).catch(()=>{});api<Integrations>('/admin/integrations').then(value=>{setIntegrations(value);setMailEnabled(value.mail.enabled);setMailHost(value.mail.host);setMailPort(String(value.mail.port));setMailUsername(value.mail.username);setMailFrom(value.mail.from);}).catch(()=>{});api<NotificationStatus>('/admin/notifications').then(value=>{setNotifications(value);setNotificationEnabled(value.enabled);setNotificationInitialDelay(String(value.initialDelaySeconds));setNotificationInterval(String(value.intervalHours));setNotificationMilestones(value.milestones.join(','));}).catch(()=>{});};
 useEffect(load,[]);
 const saveMail=async(event:React.FormEvent)=>{event.preventDefault();setMailSaving(true);setMailError('');setMailMessage('');try{const value=await api<Integrations['mail']>('/admin/integrations/mail',{method:'PUT',body:JSON.stringify({enabled:mailEnabled,host:mailHost,port:Number(mailPort),username:mailUsername,password:mailPassword||null,from:mailFrom})});setIntegrations(current=>current?{...current,mail:value}:current);setMailPassword('');setMailMessage('Mail settings saved securely.');}catch(e){setMailError(e instanceof Error?e.message:'Could not save mail settings.');}finally{setMailSaving(false);}};
 const testMail=async()=>{setTesting(true);setMailError('');setMailMessage('');try{const value=await api<{message:string}>('/admin/integrations/mail/test',{method:'POST',body:JSON.stringify({recipient:testRecipient})});setMailMessage(value.message);}catch(e){setMailError(e instanceof Error?e.message:'SMTP test failed.');}finally{setTesting(false);}};
 const saveNotifications=async(event:React.FormEvent)=>{event.preventDefault();setNotificationSaving(true);setNotificationError('');setNotificationMessage('');try{const milestones=notificationMilestones.split(',').map(value=>Number(value.trim())).filter(value=>Number.isFinite(value));const value=await api<NotificationStatus>('/admin/notifications',{method:'PUT',body:JSON.stringify({enabled:notificationEnabled,initialDelaySeconds:Number(notificationInitialDelay),intervalHours:Number(notificationInterval),milestones})});setNotifications(value);setNotificationInitialDelay(String(value.initialDelaySeconds));setNotificationInterval(String(value.intervalHours));setNotificationMilestones(value.milestones.join(','));setNotificationMessage('Renewal notification settings saved.');}catch(e){setNotificationError(e instanceof Error?e.message:'Could not save notification settings.');}finally{setNotificationSaving(false);}};
 const updateRole=async(user:AdminUser,role:string)=>{if(role===(user.roles[0]||'Reader'))return;try{await api('/admin/users/'+user.id+'/role',{method:'PUT',body:JSON.stringify({role})});load();}catch(e){setError(e instanceof Error?e.message:'Could not update user role.');}};
 const resetPassword=async(user:AdminUser)=>{const password=window.prompt(`Set a new password for ${user.email}. Use at least 12 characters.`);if(password===null)return;try{await api('/admin/users/'+user.id+'/password',{method:'POST',body:JSON.stringify({password})});setError('');setMailMessage(`Password reset for ${user.email}.`);}catch(e){setError(e instanceof Error?e.message:'Could not reset user password.');}};
 const createUser=async(event:React.FormEvent)=>{event.preventDefault();setSaving(true);setError('');try{await api('/admin/users',{method:'POST',body:JSON.stringify({email:newEmail,displayName:newDisplayName,password:newPassword,role:newRole})});setNewEmail('');setNewDisplayName('');setNewPassword('');setNewRole('Reader');load();}catch(e){setError(e instanceof Error?e.message:'Could not create user.');}finally{setSaving(false);}};
 return <>
  <div className="headline"><div><h2>Administrator</h2><p>Manage operators, mail delivery, and renewal automation.</p></div></div>
  <section className="panel integrationPanel"><div className="panelHead"><div><h2>Users</h2><p>Assign least-privilege roles, lock accounts, or reset credentials.</p></div></div><form className="adminForm" onSubmit={createUser}><div className="formGrid"><label>Email<input type="email" value={newEmail} onChange={event=>setNewEmail(event.target.value)} required/></label><label>Display name<input value={newDisplayName} onChange={event=>setNewDisplayName(event.target.value)} placeholder="Optional"/></label></div><div className="formGrid"><label>Temporary password<input type="password" value={newPassword} onChange={event=>setNewPassword(event.target.value)} minLength={12} required/></label><label>Role<select value={newRole} onChange={event=>setNewRole(event.target.value)}><option value="Reader">Reader</option><option value="CertificateOperator">Certificate operator</option><option value="Administrator">Administrator</option></select></label></div><button className="primary" disabled={saving}>{saving?'Creating...':'Create user'}</button></form><div className="tableWrap"><table><thead><tr><th>User</th><th>Role</th><th>Status</th><th>Actions</th></tr></thead><tbody>{users.map(user=><tr key={user.id}><td><b>{user.displayName}</b><span>{user.email}</span></td><td><select value={user.roles[0]||'Reader'} onChange={event=>updateRole(user,event.target.value)} aria-label={`Role for ${user.email}`}><option value="Reader">Reader</option><option value="CertificateOperator">Certificate operator</option><option value="Administrator">Administrator</option></select></td><td>{user.lockoutEnd?'Locked':'Active'}</td><td className="actions"><button onClick={async()=>{try{await api('/admin/users/'+user.id+'/lock',{method:'POST'});load();}catch(e){setError(e instanceof Error?e.message:'Could not update user.');}}}>{user.lockoutEnd?'Unlock':'Lock'}</button><button onClick={()=>resetPassword(user)}>Reset password</button></td></tr>)}</tbody></table></div>{error&&<div className="error">{error}</div>}</section>
  <section className="panel integrationPanel"><div className="panelHead"><div><h2>Mail provider</h2><p>Configure SMTP delivery for lifecycle notifications.</p></div>{integrations&&<span className={integrations.mail.configured?'statusGood':'statusWarn'}>{integrations.mail.configured?'Configured':'Not configured'}</span>}</div><form className="adminForm mailForm" onSubmit={saveMail}><label className="checkboxRow"><input type="checkbox" checked={mailEnabled} onChange={event=>setMailEnabled(event.target.checked)}/>Enable email notifications</label><div className="formGrid"><label>SMTP host<input value={mailHost} onChange={event=>setMailHost(event.target.value)} required={mailEnabled}/></label><label>Port<input type="number" min="1" max="65535" value={mailPort} onChange={event=>setMailPort(event.target.value)} required/></label></div><div className="formGrid"><label>Username<input value={mailUsername} onChange={event=>setMailUsername(event.target.value)}/></label><label>From address<input type="email" value={mailFrom} onChange={event=>setMailFrom(event.target.value)} required={mailEnabled}/></label></div><label>Password<input type="password" value={mailPassword} onChange={event=>setMailPassword(event.target.value)} placeholder="Leave blank to keep current"/></label>{mailError&&<div className="error">{mailError}</div>}{mailMessage&&<div className="notice">{mailMessage}</div>}<button className="primary" disabled={mailSaving}>{mailSaving?'Saving...':'Save mail settings'}</button></form><div className="testMail"><b>Send a test message</b><div className="toolbar"><input type="email" value={testRecipient} onChange={event=>setTestRecipient(event.target.value)} placeholder="recipient@example.com"/><button type="button" onClick={testMail} disabled={testing||!testRecipient}>{testing?'Sending...':'Send test'}</button></div></div></section>
    <section className="panel integrationPanel"><div className="panelHead"><div><h2>Renewal notifications</h2><p>Configure when expiry reminders are sent.</p></div><span className={notifications?.enabled?'statusGood':'statusWarn'}>{notifications?.enabled?'Worker enabled':'Worker disabled'}</span></div><form className="adminForm" onSubmit={saveNotifications}><label className="checkboxRow"><input type="checkbox" checked={notificationEnabled} onChange={event=>setNotificationEnabled(event.target.checked)}/>Enable renewal notifications</label><div className="formGrid"><label>Initial delay (seconds)<input type="number" min="5" max="3600" value={notificationInitialDelay} onChange={event=>setNotificationInitialDelay(event.target.value)} required/></label><label>Scan interval (hours)<input type="number" min="1" max="168" value={notificationInterval} onChange={event=>setNotificationInterval(event.target.value)} required/></label></div><label>Milestones (days)<input value={notificationMilestones} onChange={event=>setNotificationMilestones(event.target.value)} placeholder="60,30,14,7,1,0" required/><small className="fieldHint">Comma-separated values from 0 to 365.</small></label>{notificationError&&<div className="error">{notificationError}</div>}{notificationMessage&&<div className="notice">{notificationMessage}</div>}<button className="primary" disabled={notificationSaving}>{notificationSaving?'Saving...':'Save notification settings'}</button></form>{notifications?<div className="integrationCards"><article><b>Last successful send</b><span>{notifications.lastSentAt?new Date(notifications.lastSentAt).toLocaleString():'No notifications yet'}</span></article><article><b>Active milestones</b><span>{notifications.milestones.join(', ')} days</span></article></div>:<p>Loading notification status...</p>}</section>
  <section className="panel integrationPanel"><div className="panelHead"><h2>API access</h2></div>{integrations&&<div className="integrationCards"><article><b>API</b><span className="statusGood">Available</span><small>{integrations.api.basePath} - cookie authentication</small></article><article><b>SMTP credentials</b><span className={integrations.mail.credentialsConfigured?'statusGood':'statusWarn'}>{integrations.mail.credentialsConfigured?'Configured':'Not configured'}</span><small>Password is never displayed.</small></article></div>}</section>
 </>;
}
function App(){const [authed,setAuthed]=useState<boolean|null>(null),[dashboard,setDashboard]=useState<Dashboard|null>(null),[customers,setCustomers]=useState<Customer[]>([]),[services,setServices]=useState<Service[]>([]),[certs,setCerts]=useState<Cert[]>([]),[audits,setAudits]=useState<Audit[]>([]),[roles,setRoles]=useState<string[]>([]),[identity,setIdentity]=useState('admin@localhost'),[page,setPage]=useState<Page>('Dashboard'),[query,setQuery]=useState(''),[healthFilter,setHealthFilter]=useState('All'),[generate,setGenerate]=useState(false),[create,setCreate]=useState<'customer'|'service'|null>(null),[editing,setEditing]=useState<{kind:'customer'|'service';record:Customer|Service}|null>(null),[passwordChange,setPasswordChange]=useState(false),[renewal,setRenewal]=useState<RenewalDraft|null>(null),[generated,setGenerated]=useState<Generated|null>(null),[selectedCertificate,setSelectedCertificate]=useState<Cert|null>(null),[notice,setNotice]=useState('');
const load=()=>{api<Dashboard>('/dashboard').then(x=>{setDashboard(x);
setAuthed(true);
}).catch(()=>setAuthed(false));
api<Customer[]>('/customers').then(setCustomers).catch(()=>{});
 api<{email?:string;roles:string[]}>('/me').then(x=>{currentRoles=x.roles;setRoles(x.roles);if(x.email)setIdentity(x.email);}).catch(()=>{});
api<Service[]>('/services').then(setServices).catch(()=>{});
api<Audit[]>('/audit').then(setAudits).catch(()=>{});
};
useEffect(load,[]);
 useEffect(()=>{const expire=()=>{antiforgeryToken=undefined;currentRoles=[];setRoles([]);setAuthed(false);setNotice('Your session expired. Please sign in again.');};window.addEventListener('auth-expired',expire);return()=>window.removeEventListener('auth-expired',expire);},[]);
useEffect(()=>{if(page==='Audit')api<Audit[]>('/audit?search='+encodeURIComponent(query)+'&limit=200').then(setAudits).catch(()=>{});},[page,query]);
const loadCertificates=()=>api<{items:Cert[]}>('/certificates?page=1&pageSize=100&search='+encodeURIComponent(query)).then(x=>setCerts(x.items)).catch(()=>{});
useEffect(()=>{api<{items:Cert[]}>('/certificates?page=1&pageSize=100&search='+encodeURIComponent(query)).then(x=>setCerts(x.items)).catch(()=>{});},[query]);
const filtered=useMemo(()=>{const q=query.trim().toLowerCase();
return certs.filter(x=>(healthFilter==='All'||x.health===healthFilter)&&(!q||[x.name,x.customer,x.service,x.primaryOwnerEmail].some(value=>value.toLowerCase().includes(q))));
},[certs,query,healthFilter]);
const visibleCustomers=useMemo(()=>{const q=query.trim().toLowerCase();return q?customers.filter(customer=>[customer.name,customer.description,customer.customerNumber??''].some(value=>value.toLowerCase().includes(q))):customers;},[customers,query]);
const visibleServices=useMemo(()=>{const q=query.trim().toLowerCase();return q?services.filter(service=>[service.name,service.customer,service.applicationClientId??'',service.externalReference??''].some(value=>value.toLowerCase().includes(q))):services;},[services,query]);
const exportCsv=()=>{const rows=[['Customer','Service','Certificate','Thumbprint','Valid until','Owner','Health','Status','Deployment'],...filtered.map(x=>[x.customer,x.service,x.name,x.thumbprint,new Date(x.validUntil).toLocaleDateString(),x.primaryOwnerEmail,x.health,x.status,x.deploymentStatus])];const escape=(value:string)=>'"'+value.replaceAll('"','""')+'"';const blob=new Blob([rows.map(row=>row.map(escape).join(',')).join('\r\n')],{type:'text/csv;charset=utf-8'});const url=URL.createObjectURL(blob);const link=document.createElement('a');link.href=url;link.download='certificate-inventory-'+new Date().toISOString().slice(0,10)+'.csv';link.click();URL.revokeObjectURL(url);};
const startRenewal=(cert:Cert)=>{setRenewal({serviceId:cert.serviceId,name:cert.name+'-renewal',commonName:cert.subject.replace(/^CN=/,''),owner:cert.primaryOwnerEmail,previousCertificateId:cert.id});setGenerate(true);};
if(authed===null)return <div className="center">Loading secure workspace...</div>;
if(!authed)return <Login done={load}/>;
const nav:[[React.ComponentType<{size?:number}>,Page],[React.ComponentType<{size?:number}>,Page],[React.ComponentType<{size?:number}>,Page],[React.ComponentType<{size?:number}>,Page],[React.ComponentType<{size?:number}>,Page],[React.ComponentType<{size?:number}>,Page],[React.ComponentType<{size?:number}>,Page]]=[[LayoutDashboard,'Dashboard'],[FileKey2,'Certificates'],[Building2,'Customers'],[Activity,'Services'],[CalendarClock,'Renewals'],[ShieldCheck,'Admin'],[ClipboardList,'Audit']];
const visibleNav=nav.filter(([,label])=>label!=='Admin'||roles.includes('Administrator'));
const reload=()=>{load();loadCertificates();
setNotice('Changes saved successfully.');
};
const toggleManaged=async(kind:'customer'|'service',id:string,active:boolean)=>{try{await api(`/${kind==='customer'?'customers':'services'}/${id}/status`,{method:'POST',body:JSON.stringify({active:!active})});reload();}catch(e){setNotice(e instanceof Error?e.message:'Could not update record status.');}};
const cards:[string,number,string][]=[['Certificates',dashboard?.total??0,'neutral'],['Healthy',dashboard?.healthy??0,'good'],['Renewal upcoming',dashboard?.expiring60??0,'warn'],['Renewal required',(dashboard?.expiring30??0)+(dashboard?.expiring14??0),'orange'],['Critical',dashboard?.critical??0,'danger'],['Expired',dashboard?.expired??0,'dark']];
const management=page==='Customers'?'customer':page==='Services'?'service':null;
const renewals=certs.filter(x=>x.daysRemaining<=60);
return <div className="shell"><aside><div className="logo"><ShieldCheck/><span>Cert<span>Lifecycle</span></span></div><nav>{visibleNav.map(([Icon,label])=><button className={page===label?'active':''} onClick={()=>{setPage(label);
setNotice('');
}} key={label}><Icon size={18}/>{label}</button>)}</nav><div className="boundary"><ShieldCheck size={18}/><div><b>Secure boundary</b><span>No tenant connections</span></div></div></aside><main><header><div><div><h1>{page}</h1><p>Certificate lifecycle and renewal operations</p></div><div className="globalSearch"><Search size={16}/><input value={query} onChange={event=>setQuery(event.target.value)} placeholder="Search customers, services, certificates" aria-label="Search customers, services, certificates"/></div></div><button className="changePassword" type="button" onClick={()=>setPasswordChange(true)}>Password</button><button className="user" onClick={async()=>{try{await api('/auth/logout',{method:'POST'});
 }finally{antiforgeryToken=undefined;currentRoles=[];setRoles([]);
setAuthed(false);
}}}><span>LA</span>{identity}<LogOut size={16}/></button></header><section className="content">{notice&&<div className="notice">{notice}</div>}{page==='Dashboard'&&<><div className="headline"><div><h2>Certificate health</h2><p>Current expiration posture across all customers and services.</p></div><button className="primary" onClick={()=>setGenerate(true)}><Plus size={17}/>Generate certificate</button></div><div className="cards">{cards.map(([label,value,tone])=><article key={label} className={tone}><span>{label}</span><strong>{value}</strong><small>{label==='Certificates'?'Total managed records':'Based on remaining lifetime'}</small></article>)}</div><section className="panel"><div className="panelHead"><h2>Certificate inventory</h2><div className="toolbar"><div className="search"><Search size={16}/><input value={query} onChange={event=>setQuery(event.target.value)} placeholder="Search inventory"/></div><select value={healthFilter} onChange={event=>setHealthFilter(event.target.value)} aria-label="Filter certificate health"><option>All</option><option>Healthy</option><option>RenewalUpcoming</option><option>RenewalRequired</option><option>Critical</option><option>Expired</option></select><button onClick={exportCsv} title="Export filtered inventory"><Download size={16}/>Export CSV</button></div></div><CertificateTable certs={filtered} reload={reload} renew={startRenewal} inspect={setSelectedCertificate}/></section></>}{page==='Certificates'&&<><div className="headline"><div><h2>Certificate inventory</h2><p>Generate, deploy, decommission, and download renewal calendars.</p></div><button className="primary" onClick={()=>setGenerate(true)}><Plus size={17}/>Generate certificate</button></div><section className="panel"><div className="panelHead"><h2>All certificates</h2><div className="toolbar"><div className="search"><Search size={16}/><input value={query} onChange={event=>setQuery(event.target.value)} placeholder="Search inventory"/></div><select value={healthFilter} onChange={event=>setHealthFilter(event.target.value)} aria-label="Filter certificate health"><option>All</option><option>Healthy</option><option>RenewalUpcoming</option><option>RenewalRequired</option><option>Critical</option><option>Expired</option></select><button onClick={exportCsv} title="Export filtered inventory"><Download size={16}/>Export CSV</button></div></div><CertificateTable certs={filtered} reload={reload} renew={startRenewal} inspect={setSelectedCertificate}/></section></>}{management&&<><div className="headline"><div><h2>{page}</h2><p>Manage records used by certificate generation.</p></div><button className="primary" onClick={()=>setCreate(management)}><Plus size={17}/>Create {management}</button></div><section className="panel"><div className="tableWrap"><table><thead><tr><th>Name</th><th>Identifier</th><th>Details</th><th>Status</th><th>Actions</th></tr></thead><tbody>{management==='customer'&&visibleCustomers.map(x=><tr key={x.id}><td>{x.name}</td><td><code>{x.id}</code></td><td>{x.customerNumber||'-'}</td><td><i className={'badge '+(x.isActive?'healthy':'expired')}>{x.isActive?'Active':'Archived'}</i></td><td className="actions"><button onClick={()=>setEditing({kind:'customer',record:x})}>Edit</button><button onClick={()=>toggleManaged('customer',x.id,x.isActive)}>{x.isActive?'Archive':'Restore'}</button></td></tr>)}{management==='service'&&visibleServices.map(x=><tr key={x.id}><td>{x.name}</td><td><code>{x.id}</code></td><td><span>{x.customer}</span><code>{x.applicationClientId||'No client ID'}</code><i className={'badge '+(x.certificateReady?'healthy':'expired')}>{x.certificateReady?'SP ready':'Add client ID'}</i></td><td><i className={'badge '+(x.isActive?'healthy':'expired')}>{x.isActive?'Active':'Archived'}</i></td><td className="actions"><button onClick={()=>setEditing({kind:'service',record:x})}>Edit</button><button onClick={()=>toggleManaged('service',x.id,x.isActive)}>{x.isActive?'Archive':'Restore'}</button></td></tr>)}</tbody></table></div></section></>}{page==='Admin'&&<AdminPanel/>}{page==='Renewals'&&<><div className="headline"><div><h2>Renewals</h2><p>Certificates expiring within 60 days or already expired.</p></div></div><section className="panel"><CertificateTable certs={renewals} reload={reload} renew={startRenewal} inspect={setSelectedCertificate} empty="No upcoming renewals"/></section></>}{page==='Audit'&&<><div className="headline"><div><h2>Audit history</h2><p>Recent security and lifecycle actions.</p></div></div><section className="panel"><div className="tableWrap"><table><thead><tr><th>When</th><th>Action</th><th>Entity</th><th>Result</th></tr></thead><tbody>{audits.map(a=><tr key={a.id}><td>{new Date(a.timestamp).toLocaleString()}</td><td>{a.action}</td><td>{a.entityType} <code>{a.entityId}</code></td><td>{a.result}</td></tr>)}</tbody></table></div></section></>}</section></main>{generate&&<GenerateDialog services={services.filter(service=>service.isActive)} initial={renewal??undefined} close={()=>{setGenerate(false);setRenewal(null);}} done={result=>{setGenerate(false);setRenewal(null);
setGenerated(result);
reload();
}}/>}{generated&&<ArtifactDialog result={generated} close={()=>setGenerated(null)}/>}{selectedCertificate&&<CertificateDetailDialog id={selectedCertificate.id} close={()=>setSelectedCertificate(null)}/>}{create&&<CreateDialog kind={create} customers={customers} close={()=>setCreate(null)} done={()=>{setCreate(null);
reload();
}}/>}{editing&&<EditDialog kind={editing.kind} record={editing.record} close={()=>setEditing(null)} done={()=>{setEditing(null);
reload();
}}/>}{passwordChange&&<PasswordDialog close={()=>setPasswordChange(false)} done={()=>{setPasswordChange(false);setNotice('Password changed successfully.');}}/>}</div>;
}
createRoot(document.getElementById('root')!).render(<React.StrictMode><App/></React.StrictMode>);
